# Generated by Django 5.2.6 on 2025-09-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='options',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
