# Generated by Django 5.2.6 on 2025-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_studentprofile_user_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
